In [4]:
import numpy as np
a=np.zeros(3)
#是float格式的
a

array([0., 0., 0.])

In [9]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
z.shape

(10,)

In [13]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [14]:
z=np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
z=np.empty(3)
z

array([0., 0., 0.])

In [18]:
z=np.linspace(2,18,5) #从2到18,平均取5个元素
z

array([ 2.,  6., 10., 14., 18.])

In [19]:
z=np.array([10,20])
z

array([10, 20])

In [21]:
a_list=[1,2,3,4,5,6,7,8,9]
z=np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
b_list=[[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z=np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [26]:
?z.shape

In [29]:
np.random.seed(0)
z1=np.random.randint(10,size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [30]:
z1[0]

5

In [31]:
z1[0:2]

array([5, 0])

In [32]:
z1[-1]

9