# numpy基础

In [1]:
import numpy as np
array = np.array([[1,2,3,4],[2,3,4,5]])  #列表转化为矩阵
print(array)

print('number of dim:',array.ndim)  # 维度  .ndim
# number of dim: 2

print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)

print('size:',array.size)   # 元素个数
# size: 8

[[1 2 3 4]
 [2 3 4 5]]
number of dim: 2
shape : (2, 4)
size: 8


array：创建数组

dtype：指定数据类型

zeros：创建数据全为0

ones：创建数据全为1

empty：创建数据接近0

arrange：按指定范围创建数据

linspace：创建线段


In [9]:
a = np.array([2,23,4])  # 列表a
print(a) #答案没有逗号,
a = np.array([2,23,4],dtype=np.int)  #可以定义32位  int32 即可
print(a.dtype)
print(a)
a = np.array([2,23,4],dtype=np.float)  #可以定义32位  float32 即可
print(a.dtype)
print(a)

[ 2 23  4]
int64
[ 2 23  4]
float64
[ 2. 23.  4.]


创建特定数据:特定矩阵、0、1、空

In [12]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [15]:
a = np.zeros((3,4)) # 数据全为0，3行4列
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
a = np.empty((3,4)) # 数据为empty，3行4列
print(a)

[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]


In [35]:
a1 = np.arange(10,20,2) # 10-19 的数据，2步长
a2 = np.arange(2,14).reshape((3,4))    # 3行4列，0到11
a22 = np.arange(12).reshape((3,4))    # 3行4列，0到11
a3 = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
a4 = np.linspace(1,10,20).reshape((5,4)) # 更改shape
print('a1--------------------')
print(a1)
print('a2--------------------')
print(a2)
print('a22--------------------')
print(a22)
print('a3--------------------')
print(a3)
print('a4--------------------')
print(a4)

a1--------------------
[10 12 14 16 18]
a2--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
a22--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3--------------------
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
a4--------------------
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


# NumPy 基础运算1 
## 一维运算

In [47]:
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)         # array([0, 1, 2, 3])
print('a',a)
print('b',b)
c=a-b    #矩阵减法
print('c',c)

a [10 20 30 40]
b [0 1 2 3]
c [10 19 28 37]


In [48]:
d=a+b
print (d)

[10 21 32 43]


In [49]:
e=a*b   # array([  0,  20,  60, 120])
print(e)

[  0  20  60 120]


In [50]:
f=b**2  # array([0, 1, 4, 9])
print(f)

[0 1 4 9]


In [58]:
g=10*np.sin(a)  
print(g)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [65]:
print(b<2)
print(b==3)

[[ True  True]
 [False False]]
[[False False]
 [False  True]]


## 二纬运算

In [63]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [68]:
c=a*b
d=np.dot(a,b)
print(c,end='\n\n')
print(d)
print('')
d2= a.dot(b) #a dot b的第二种形式
print(d2)

[[0 1]
 [0 3]]

[[2 4]
 [2 3]]

[[2 4]
 [2 3]]


In [73]:
#经过研究测试一下 应该是[[3,6],[7,14]]

a=np.arange(1,5).reshape((2,2))
b=np.array([[1,2],[1,2]])
c=a.dot(b)
print(a)
print(b)
print(c)



[[1 2]
 [3 4]]
[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]]


[所以，dot就是行成列的和，作为一个元素,点击参考百度链接：](https://baike.baidu.com/item/%E7%9F%A9%E9%98%B5%E4%B9%98%E6%B3%95/5446029?fr=aladdin)

## 随机生成序列矩阵

In [76]:
a=np.random.random((2,4))  #随机生成2行四列
print(a)

[[0.58411757 0.67044761 0.65859751 0.55981163]
 [0.93236608 0.64997618 0.03785699 0.02292278]]


In [80]:
print(np.sum(a))   # 4.4043622002745959
print(np.min(a) )  # 0.23651223533671784
print(np.max(a) )  # 0.90438450240606416

4.116096352363905
0.022922781710752793
0.9323660800626806


In [82]:
print("a =",a)

print("sum =",np.sum(a,axis=1))
print('sum =',np.sum(a))
print("min =",np.min(a,axis=0))

print("max =",np.max(a,axis=1))
# 如果你需要对行或者列进行查找运算，就需要在上述代码中为 axis 进行赋值。 
# 当axis的值为0的时候，将会以列作为查找单元， 当axis的值为1的时候，将会以行作为查找单元。
# 这块挺乱哈

a = [[0.58411757 0.67044761 0.65859751 0.55981163]
 [0.93236608 0.64997618 0.03785699 0.02292278]]
sum = [2.47297432 1.64312204]
sum = 4.116096352363905
min = [0.58411757 0.64997618 0.03785699 0.02292278]
max = [0.67044761 0.93236608]


# NumPy 基础运算2

## 其中的 argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引。相应的，在矩阵的12个元素中，最小值即2，对应索引0，最大值为13，对应索引为11。

In [96]:
A = np.arange(2,14).reshape((3,4)) 
B = np.array([[2,3,4],[1,1,1],[8,9,55]])
print(A)

print('')
         
print(np.argmin(A))    # 0  个位置
print(np.argmax(A))    # 11 个位置

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

0
11


## 如果需要计算统计中的均值，可以利用下面的方式，将整个矩阵的均值求出来：

In [87]:
print(np.mean(A))        # 7.5
print(np.average(A))     # 7.5
print(A.mean())          # 7.5

7.5
7.5
7.5


## 同样的，我们可以写出求解中位数的函数：

In [92]:
print(np.median(A))       # 7.5
#print(A.median())       # 7.5 这个方式用不了

7.5


## 数组累加：
在cumsum()函数中：生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和。

In [99]:
print(A)
print(' ')
print(B)
print(' ')
print(np.cumsum(A)) 
print(np.cumsum(B)) 

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
 
[[ 2  3  4]
 [ 1  1  1]
 [ 8  9 55]]
 
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[ 2  5  9 10 11 12 20 29 84]


相应的有累差运算函数：该函数计算的便是每一行中后一项与前一项之差。故一个3行4列矩阵通过函数计算得到的矩阵便是3行3列的矩阵。

In [101]:
print(np.diff(A))
print(' ')
print(np.diff(B))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
 
[[ 1  1]
 [ 0  0]
 [ 1 46]]


## 进行sort运算

In [106]:
A = np.arange(14,2, -1).reshape((3,4)) 
print(A)
print('下边进行sort运算:::',end='\n\n')
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
下边进行sort运算:::

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


## 矩阵的转置有两种表示方法：

In [108]:
print(np.transpose(A),end='\n\n')    
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


## 特别的，在Numpy中具有clip()函数，例子如下：
这个函数的格式是clip(Array,Array_min,Array_max)，顾名思义，Array指的是将要被执行用的矩阵，而后面的最小值最大值则用于让函数判断矩阵中元素是否有比最小值小的或者比最大值大的元素，并将这些指定的元素转换为最小值或者最大值。

In [111]:
print(A)

print('\n\n')
print(np.clip(A,5,9))    


[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]



[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
