## 两个array竖向合并

In [1]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))

[[1 1 1]
 [2 2 2]]


vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作。此时我们对组合而成的矩阵进行属性探究：

In [4]:
C = np.vstack((A,B))
print(C)
print(A.shape,C.shape)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)


⬆️ 利用shape函数可以让我们很容易地知道A和C的属性，从打印出的结果来看，A仅仅是一个拥有3项元素的数组（数列），而合并后得到的C是一个2行3列的矩阵。

## 我们来说说左右合并：

In [5]:
D = np.hstack((A,B))       # horizontal stack

print(D)
print(A.shape,D.shape)

[1 1 1 2 2 2]
(3,) (6,)


通过打印出的结果可以看出：D本身来源于A，B两个数列的左右合并，而且新生成的D本身也是一个含有6项元素的序列。

## np.newaxis() 
我们稍稍提及一下前一节中转置操作，如果面对如同前文所述的A序列， 转置操作便很有可能无法对其进行转置（因为A并不是矩阵的属性），此时就需要我们借助其他的函数操作进行转置：

In [9]:
print(A)
print(A[np.newaxis,:])
print('---------------------------')
print(A[np.newaxis,:].shape)
print('---------------------------')
print(A[:,np.newaxis])
print('---------------------------')
print(A[:,np.newaxis].shape)

[1 1 1]
[[1 1 1]]
---------------------------
(1, 3)
---------------------------
[[1]
 [1]
 [1]]
---------------------------
(3, 1)


合并着用

In [13]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print('---------------------------')        
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack
print(C)
print('---------------------------')
print(D)
print('---------------------------')
print(A.shape,D.shape)

---------------------------
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
---------------------------
[[1 2]
 [1 2]
 [1 2]]
---------------------------
(3, 1) (3, 2)


当你的合并操作需要针对多个矩阵或序列时，借助concatenate函数可能会让你使用起来比前述的函数更加方便：

In [32]:
A = np.array([1,1,1])
B = np.array([2,2,2])
C=np.concatenate((A,B),axis=0)
print(C)
print(':::::::::::::::::::::::::::')
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
C=np.concatenate((A,B),axis=0)
print(C)
print(':::::::::::::::::::::::::::')
D=np.concatenate((A,B),axis=1)
print(D)

[1 1 1 2 2 2]
:::::::::::::::::::::::::::
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
:::::::::::::::::::::::::::
[[1 2]
 [1 2]
 [1 2]]


# 分割

In [33]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


分割1 纵向： 2的意思是分成两个array

In [42]:
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


分割2 横向： 3的意思是分成三个array

In [43]:
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


不等量的分割

In [47]:
print(np.array_split(A, 2, axis=0))
print(np.array_split(A, 3, axis=1))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


其他的分割方式，在Numpy里还有np.vsplit()与横np.hsplit()方式可用。


In [54]:
print(np.vsplit(A, 3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
