# Numpy 赋值

In [2]:
import numpy as np

a = np.arange(4)
print(a)

[0 1 2 3]


改变a的第一个值，b、c、d的第一个值也会同时改变。

In [3]:
a[0] = 11
print(a)

[11  1  2  3]


In [4]:
b = a
c = a
d = b

确认b、c、d是否与a相同。

In [5]:
b is a  # True
c is a  # True
d is a  # True

True

同样更改d的值，a、b、c也会改变。

In [6]:
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


# deep copy
copy() 的赋值方式没有关联性

In [7]:
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
