# 一维索引

In [2]:
import numpy as np
A = np.arange(3,15)
print(A)  
print(A[3]) 

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


# 二维索引
## 一般情况：
让我们将矩阵转换为二维的，此时进行同样的操作：

In [4]:
A = np.arange(3,15).reshape((3,4))
print(A) 
print('_____')
print(A[2])  

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
_____
[11 12 13 14]


想要表示具体的单个元素，可以仿照上述的例子：

In [6]:
print(A[1][1])   
print(A[2][1])

8
12


同样的还有其他的表示方法：

In [8]:
print(A[2, 1])  #去了【】符号

12


在Python的 list 中，我们可以利用:对一定范围内的元素进行切片操作，在Numpy中我们依然可以给出相应的方法：

In [20]:
print(A[1,:])       # 用冒号：代表第一行内的 “所有数“
print(A[1, 1:3])    # 打印第一行，1-3元素
print(A[:,1])          # 用冒号：代表第一列的“所有数”

[ 7  8  9 10]
[8 9]
[ 4  8 12]


我们适当的利用for函数进行打印：

In [23]:
for row in A:
    print('~~~~~')
    print(row)


~~~~~
[3 4 5 6]
~~~~~
[ 7  8  9 10]
~~~~~
[11 12 13 14]


此时它会逐行进行打印操作。如果想进行逐列打印，就需要稍稍变化一下：

转置T进行行列调换，然后进行打印


In [24]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


最后依然说一些关于迭代输出的问题：

这一脚本中的flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列。而flat是一个迭代器，本身是一个object属性。

In [27]:
import numpy as np
A = np.arange(3,15).reshape((3,4))
         
print(A.flatten())   

for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
